### ISSUE TITLE
ssl certificate verify failed 

### ISSUE THREAD

**Issue by kamidorik** [joshua-stone/DerPyBooru#17]
Traceback` (most recent call last):
  File "C:\Py3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "C:\Py3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "C:\Py3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "C:\Py3\lib\site-packages\requests\packages\urllib3\connection.py", line 323, in connect
    ssl_context=context)
  File "C:\Py3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Py3\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Py3\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Py3\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Py3\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Py3\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Py3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 624, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\raritybot.py", line 4, in <module>
    for image in Search().query("rarity", "safe"):
  File "C:\Py3\lib\site-packages\derpibooru\search.py", line 206, in __next__
    return Image(next(self._search))
  File "C:\Py3\lib\site-packages\derpibooru\request.py", line 74, in get_images
    for index, image in enumerate(r, start=1):
  File "C:\Py3\lib\site-packages\derpibooru\request.py", line 53, in request
    request = get(search, params=p)
  File "C:\Py3\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Py3\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Py3\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Py3\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Py3\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

**Comment by BytewaveMLP** [comment]
Works fine for me. Are you sure your system date is set correctly?

**Comment by LoganDark** [comment]
Your python was compiled without ssl support. Have fun.
