### ISSUE TITLE
Animated (.gif) images without webm representations throw KeyError

### ISSUE THREAD

**Issue by BytewaveMLP** [joshua-stone/DerPyBooru#18]
```
Traceback (most recent call last):
  (application-specifc details)
  File "randibooru.py", line 36, in on_message
    results = list(search)
  File "/usr/local/lib/python3.5/dist-packages/derpibooru/search.py", line 206, in __next__
    return Image(next(self._search))
  File "/usr/local/lib/python3.5/dist-packages/derpibooru/image.py", line 49, in __init__
    setattr(self, "webm", self.representations["webm"])
KeyError: 'webm'
```

This occurs because of [this statement](https://github.com/joshua-stone/DerPyBooru/blob/master/derpibooru/image.py#L48-L50), where the library attempts to overzealously populate the `webm` and `mp4` properties without making sure the API returns them as possible `representation`s.

**Comment by BytewaveMLP** [comment]
Whoops, probably should've checked. Looks like this would be closed by #7.
